name: 'Hello World'
description: 'Greet someone'
inputs:
  aws-region:
    description: "The aws region to push the data"
    required: true
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{inputs.aws-region}}
          role-to-assume: arn:aws:iam::098481452419:role/github-actions
          role-session-name: CDPush-${{inputs.aws-region}}
      - name: CDPush to ${{inputs.aws-region}}
        id: cdpush-${{inputs.aws-region}}
        shell: bash
        run: |
          set -x
          export NEEVA_REPO=$(git rev-parse --show-toplevel)
          echo "::set-output name=cdpushed_files::${files}"
      - uses: actions/github-script@v6
        env:
          CDPUSHED: ${{ steps.cdpush-us-east-1.outputs.cdpushed_files }}
        with:
          script: |
            cdpushed = process.env.CDPUSHED
            if (cdpushed.length === 0) {
              return
            }
            files = cdpushed.split(",")
            let body = "### CDPush to us-east-1 succeeded!\n"
            for (const file of files) {
                body += `✅ CDPushed \`${file}\` to \`s3://neeva-cdpush-us-east-1/cdpush\`\n`
            }
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })
