name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Configure AWS Credentials For ${{inputs.who-to-greet}}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{inputs.who-to-greet}}
          role-to-assume: arn:aws:iam::098481452419:role/github-actions
          role-session-name: CDPush-us-east-1
      - name: CDPush to us-east-1
        id: cdpush-us-east-1
        shell: bash
        env:
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          export NEEVA_REPO=$(git rev-parse --show-toplevel)
          commit=$(gh pr view $PR_NUMBER --json mergeCommit | jq .mergeCommit.oid | tr -d '"')
          short_commit=$(git rev-parse --short $commit)
          # see http://mywiki.wooledge.org/BashFAQ/024 for why dumping into a file
          gh pr view $PR_NUMBER  --json files --jq '.files.[].path' | grep '^serving/cdpush/data' > files.txt
          while read -r file; do
            if test -f $file; then
              echo CDPushing $file
              if [ -z ${files+x} ]; then
                files=${file}
              else
                files=${files},${file}
              fi
            else
              echo skipping deleted file: $file
            fi
          done < files.txt
          echo "::set-output name=cdpushed_files::${files}"
      - uses: actions/github-script@v6
        env:
          CDPUSHED: ${{ steps.cdpush-us-east-1.outputs.cdpushed_files }}
        with:
          script: |
            cdpushed = process.env.CDPUSHED
            if (cdpushed.length === 0) {
              return
            }
            files = cdpushed.split(",")
            let body = "### CDPush to us-east-1 succeeded!\n"
            for (const file of files) {
                body += `✅ CDPushed \`${file}\` to \`s3://neeva-cdpush-us-east-1/cdpush\`\n`
            }
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })
