name: 'Hello World'
description: 'Greet someone'
inputs:
  aws-region:
    description: "The aws region to push the data"
    required: true
  github-token:
    description: "The Github token for running github cli"
    required: true
runs:
  using: "composite"
  steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{inputs.aws-region}}
          role-to-assume: arn:aws:iam::098481452419:role/github-actions
          role-session-name: CDPush-${{inputs.aws-region}}
      - name: CDPush
        id: cdpush
        shell: bash
        env:
          GH_TOKEN: ${{ inputs.github-token }}
        run: |
          set -x
          export PR_NUMBER=113
          export NEEVA_REPO=$(git rev-parse --show-toplevel)
          commit=$(gh pr view $PR_NUMBER --json mergeCommit | jq .mergeCommit.oid | tr -d '"')
          short_commit=$(git rev-parse --short $commit)
          # see http://mywiki.wooledge.org/BashFAQ/024 for why dumping into a file
          gh pr view $PR_NUMBER  --json files --jq '.files.[].path' > files.txt
          while read -r file; do
            if test -f $file; then
              echo CDPushing $file
              if [ -z ${files+x} ]; then
                files=${file}
              else
                files=${files},${file}
              fi
            else
              echo skipping deleted file: $file
            fi
          done < files.txt
          echo "::set-output name=cdpushed_files::${files}"
      - uses: actions/github-script@v6
        env:
          CDPUSHED: ${{ steps.cdpush.outputs.cdpushed_files }}
        with:
          script: |
            cdpushed = process.env.CDPUSHED
            if (cdpushed.length === 0) {
              return
            }
            files = cdpushed.split(",")
            let body = "### CDPush to us-east-1 succeeded!\n"
            for (const file of files) {
                body += `✅ CDPushed \`${file}\` to \`s3://neeva-cdpush-us-east-1/cdpush\`\n`
            }
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })
