name: CDPush
on:
  pull_request:
    types:
      - closed
    paths:
      - "serving/cdpush/data/**"
jobs:
  trigger-cdpush:
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::098481452419:role/github-actions
          role-session-name: CDPush-US-EAST-1
      - name: CDPush to us-east-1
        id: cdpush-us-east-1
        env:
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          export NEEVA_REPO=$(git rev-parse --show-toplevel)
          commit=$(gh pr view $PR_NUMBER --json mergeCommit | jq .mergeCommit.oid | tr -d '"')
          short_commit=$(git rev-parse --short $commit)
          gh pr view $PR_NUMBER  --json files --jq '.files.[].path' | grep '^serving/cdpush/data' | while read -r file; do
            if test -f $file; then
              echo CDPushing $file
              #cli/cli.sh cdpush --data_files $file --s3_prefix=s3://neeva-cdpush-us-east-1/ -r us-east-1 --commit_hash $short_commit
              if [ -z ${files+x} ]; then
                files=${file}
                files=${files},${file}
                echo ${files}
                echo $files
              else
                files=${files},${file}
                echo ${files}
                echo $files
              fi
            else
              echo skipping deleted file: $file
            fi
          done
          echo aaa
          echo ${files}
          echo "::set-output name=cdpushed_files::aaa"
      - uses: actions/github-script@v6
        env:
          PR_NUMBER: ${{ steps.cdpush-us-east-1.outputs.cdpushed_files }}
        with:
          script: |
            const { PR_NUMBER } = process.env

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${PR_NUMBER}`
            })
      - name: Configure AWS Credentials For us-west-2
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::098481452419:role/github-actions
          role-session-name: CDPush-US-WEST-2
      - name: CDPush to us-west-2
        env:
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          export NEEVA_REPO=$(git rev-parse --show-toplevel)
          export NEEVA_REPO="$(git rev-parse --show-toplevel)"
          commit=$(gh pr view $PR_NUMBER --json mergeCommit | jq .mergeCommit.oid | tr -d '"')
          short_commit=$(git rev-parse --short $commit)
          echo $(git diff-tree --no-commit-id --name-only -r $commit)
          gh pr view $PR_NUMBER  --json files --jq '.files.[].path' | grep '^serving/cdpush/data' | while read -r file; do
            if test -f $file; then
              echo CDPushing $file
              cli/cli.sh cdpush --data_files $file --s3_prefix=s3://neeva-cdpush-us-west-2/ -r us-west-2 --commit_hash $short_commit
            else
              echo skipping deleted file: $file
            fi
          done
