name: CDPush
on:
  pull_request:
    types:
      - closed
    paths:
      - "serving/cdpush/data/**"
jobs:
  trigger-cdpush:
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - id: CDPush-us-east-1
        uses: ./.github/actions/cdpush
        with:
          aws-region: 'us-east-1'
          aws-bucket: 's3://neeva-cdpush-us-east-1'
          pull-request: ${{ github.event.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - id: CDPush-us-west-2
        uses: ./.github/actions/cdpush
        with:
          aws-region: 'us-west-2'
          aws-bucket: 's3://neeva-cdpush-us-west-2'
          pull-request: ${{ github.event.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
