name: CDPush
on:
  pull_request:
    types:
      - closed
    paths:
      - "serving/cdpush/data/**"
jobs:
  trigger-cdpush:
    permissions:
      id-token: write
      contents: read
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::098481452419:role/github-actions
          role-session-name: CDPush-US-EAST-1
      - name: CDPush to us-east-1
        env:
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          export NEEVA_REPO="$(git rev-parse --show-toplevel)"
          eval $(go run neeva.co/cmd/prodaccess aws shell --eval)
          files=$(gh pr view $PR_NUMBER  --json files --jq '.files.[].path' | grep '^serving/cdpush/data' | awk -v d=" " '{s=(NR==1?s:s d)$0}END{print s}')
          commit=$(gh pr view $PR_NUMBER --json mergeCommit | jq .mergeCommit.oid | tr -d '"')
          commit=$(git rev-parse --short $commit)
          echo CDPushing $files
          cli/cli.sh cdpush --data_files $files --s3_prefix=s3://neeva-cdpush-us-east-1/ -r us-east-1 --commit_hash $commit
      - name: Configure AWS Credentials For us-west-2
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::098481452419:role/github-actions
          role-session-name: CDPush-US-WEST-2
      - name: CDPush to us-west-2
        env:
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          export NEEVA_REPO="$(git rev-parse --show-toplevel)"
          eval $(go run neeva.co/cmd/prodaccess aws shell --eval)
          files=$(gh pr view $PR_NUMBER  --json files --jq '.files.[].path' | grep '^serving/cdpush/data' | awk -v d=" " '{s=(NR==1?s:s d)$0}END{print s}')
          commit=$(gh pr view $PR_NUMBER --json mergeCommit | jq .mergeCommit.oid | tr -d '"')
          commit=$(git rev-parse --short $commit)
          echo CDPushing $files
          cli/cli.sh cdpush --data_files $files --s3_prefix=s3://neeva-cdpush-us-west-2/ -r us-west-2 --commit_hash $commit
