name: Feature Flag Check
on:
  pull_request:
    types:
      - closed
    paths:
      - "serving/cdpush/data/**"
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The PR was merged

